<section id="functions" class="section">
  <h2>How a function generates points</h2>
  <p>A function is a rule that accepts an allowed input $x$ and produces exactly one output $y=f(x)$. The ordered pair $(x,f(x))$ is then placed in the Cartesian plane.</p>

  <figure class="figure-panel jsx-panel function-machine-panel" data-fullscreen-panel tabindex="0">
    <div class="figure-toolbar">
      <div>
        <span class="figure-title">From an input to a point</span>
        <span class="figure-step-title" data-function-equation>$y=2x+1$</span>
      </div>
      <button class="icon-button" type="button" data-fullscreen aria-label="Open function construction in full screen">⛶</button>
    </div>

    <div class="curve-switcher" role="group" aria-label="Choose a function">
      <button class="curve-mode is-active" type="button" data-function-mode="linear">Linear function</button>
      <button class="curve-mode" type="button" data-function-mode="inverse">Inverse proportionality</button>
    </div>

    <div class="function-workflow" aria-live="polite">
      <div><span class="workflow-label">Choose input</span><strong data-input-step>$x=1$</strong></div>
      <div><span class="workflow-label">Substitute</span><strong data-substitution-step>$y=2\cdot1+1$</strong></div>
      <div><span class="workflow-label">Calculate</span><strong data-output-step>$y=3$</strong></div>
      <div><span class="workflow-label">Plot</span><strong data-point-step>$(1,3)$</strong></div>
    </div>

    <div class="figure-stage jsx-stage">
      <div id="function-machine-board" class="jxgbox" data-function-machine aria-label="Interactive construction of points generated by a function"></div>
    </div>

    <div class="parameter-controls function-input-control">
      <label class="parameter-control">
        <span>input $x$ = <output data-function-x>1</output></span>
        <input type="range" min="-4" max="4" step="0.5" value="1" data-function-x-slider aria-label="Input x">
      </label>
    </div>

    <figcaption class="figure-caption">Move the input slider. The substitution, output and point update together. Previously generated points remain faintly visible.</figcaption>
  </figure>

  <div class="statement">
    <div class="statement-label">Function test</div>
    <p>For each allowed value of $x$, a function gives one and only one value of $y$. The graph is the collection of all points $(x,f(x))$.</p>
  </div>
</section>